### ISSUE TITLE
Bugs / reduced features on Ubuntu (Gnome)

### ISSUE THREAD

**Issue by MrFly** [marcus67/little_brother_taskbar#33]
There are some missing features at 0.4.11 if using the taskbar in a Gnome 3 environment.

In Gnome there is no task icon, therefore it's not possible to change/open the configuration by mouse click. And some strange thing: Clicking in the dialog closes the taskbar - because there is no task icon, I'm not able to open it again.

A good solution could be maybe to develop a Gnome Shell Extension (https://extensions.gnome.org/), which could resolve any of this issues.

**Comment by marcus67** [comment]
The application `little_brother_taskbar` uses the wxPython package to interact with the XWindows system including the system tray functionality. Unfortunately, the specifications for the latter vary across the windows managers and their versions. In modern versions of Gnome, for example, the tray icons provided by wxPython are no longer supported. However, there is a Gnome extension which can be installed using a Debian package which shows all "old-fashioned" tray icons in the modern Gnome toolbar at the top of the screen. See the caveats section of the [README](https://github.com/marcus67/little_brother_taskbar/blob/master/README.md).

**Comment by MrFly** [comment]
Hi Marcus,

Thanks a lot. With this extension it works. I will try it more and better, but the first test was as expected.
